name: release prod

on: 
  workflow_call: ~
  push:
    tags:
      - 'v*'

jobs:
  # coding-style:
  #   name: Probe NodeJs - Code Style
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: nick-fields/retry@v3
  #       with:
  #         max_attempts: 3
  #         retry_on: error
  #         timeout_minutes: 3
  #         command: |
  #           docker compose build nodejs --build-arg NODE_VERSION=latest
  #           docker compose run --rm nodejs /bin/sh -c -e 'make eslint'

  # unit-tests:
  #   name: Probe Node.js ${{ matrix.version }} Continuous Profiling Probe - Unit tests
  #   runs-on: ubuntu-latest
  #   needs: coding-style
  #   timeout-minutes: 3
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       version: 
  #       - 18
  #       # - 20
  #       # - 21
  #       # - 22
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: nick-fields/retry@v3
  #       with:
  #         max_attempts: 3
  #         retry_on: error
  #         timeout_minutes: 3
  #         command: |
  #           docker compose build nodejs --build-arg NODE_VERSION=${{ matrix.version }}
  #           docker compose run --rm nodejs /bin/sh -c -e 'make test'

  release:
    name: Probe NodeJs - Release
    runs-on: ubuntu-latest
    # needs: unit-tests
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      
      - uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 3
          command: |
            run: echo "TAG: $TAG"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          FOO: "BAR"
          TAG: ${{ github.ref_name }}

  #       - "/var/lib/buildkite-agent/pipelines/nodejs-probe/release.sh:/blackfire/release.sh"
  #       - "/etc/secret/tortue-geniale-github-token.sh:/etc/secret/tortue-geniale-github-token.sh"
  #       - "/etc/secret/npm.sh:/etc/secret/npm.sh"
