name: release staging

on:
  workflow_call: ~
  # push:
  #   branches:
  #     - master

jobs:
  coding-style:
    name: Probe NodeJs - Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 3
          command: |
            docker compose build nodejs --build-arg NODE_VERSION=latest
            docker compose run --rm nodejs /bin/sh -c -e 'make eslint'

  unit-tests:
    name: Probe Node.js ${{ matrix.version }} Continuous Profiling Probe - Unit tests
    runs-on: ubuntu-latest
    needs: coding-style
    timeout-minutes: 3
    strategy:
      fail-fast: false
      matrix:
        version: 
        - 18
        - 20
        - 21
        - 22
    steps:
      - uses: actions/checkout@v4

      - uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 3
          command: |
            docker compose build nodejs --build-arg NODE_VERSION=${{ matrix.version }}
            docker compose run --rm nodejs /bin/sh -c -e 'make test'
