name: release staging

on:
  push:
    branches:
      - master

jobs:
  coding-style:
    name: Probe NodeJs - Code Style
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 3
          command: |
            make eslint

  unit-tests:
    name: Probe Node.js ${{ matrix.version }} - Unit tests
    runs-on: ubuntu-latest
    needs: coding-style
    timeout-minutes: 3
    strategy:
      fail-fast: false
      matrix:
        version:
        - 18
        - 20
        - 21
        - 22
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 3
          command: |
            make test
